### ISSUE TITLE
2D annotation tool

### ISSUE THREAD

**Issue by wangyidong3** [jonasf94/threed_od#1]
Hi, Jonas
Thank you for your great work. 
Do you have any suggestions for  own dataset preparation and training on votenet with good enough result? 
Could you please provide the link of Robotron 2D annotation tool? what's the format for 2D labels?

Thanks.

**Comment by jo-chr** [comment]
Any RGB-D dataset should be sufficient to train on. As this was a project in cooperation with a compnay that annotation tool is not open source. [LabelImg](https://github.com/tzutalin/labelImg) is a good tool to annotate 2D data.

**Comment by wangyidong3** [comment]
Thank you for your advices. 
Just found that [Lableme](https://github.com/wkentaro/labelme) can help me to get json label file, which can skip xml2json convert.
