### ISSUE TITLE
using pointcloud only, with out the 2d data in transform_to_votenet_format.py

### ISSUE THREAD

**Issue by madinwei** [jonasf94/threed_od#3]
Hello @jo-chr, first thank you for you annotation tool and your work.

I have pointcloud data and i used your tool to label them. I don't have the 2d data, and when i use the [transform_to_votenet_format.py](https://github.com/jo-chr/threed_od/blob/master/preprocessing/transform_to_votenet_format.py) it need the 2d data which I don't have and Its not important for me. 
Is it possible if  guide me to how to modify [transform_to_votenet_format.py](https://github.com/jo-chr/threed_od/blob/master/preprocessing/transform_to_votenet_format.py) code to just prepare the 3d data. or any suggestion that might help.

**Comment by jo-chr** [comment]
Hi @madinwei, 

you need to adjust the write_labels() function in transform_to_votenent_format.py. Just omit all the lines of code that refer to 2D labels. 

Besides, please have a look at [labelCloud](https://github.com/ch-sa/labelCloud). It is a great new open source 3D Computer Vision annotation tool.

**Comment by madinwei** [comment]
I am very thankful for your replay @jo-chr , it worked as you said. 
I will make sure to check out [LabelCloud](https://github.com/ch-sa/labelCloud).
